### ISSUE TITLE
Run Elm format on templates

### ISSUE THREAD

**Issue by lpil** [tom76kimo/generator-elm-app#2]
Hello!

I noticed that the code style used in the templates is inconsistent in terms of spacing and indentation. Elm format is a tool that ensures consistency by managing your code style for you when you save a file. Would you consider using it in this project? https://github.com/avh4/elm-format

Thanks,
Louis

**Comment by tom76kimo** [comment]
Sure! Thanks for the info!

**Comment by tom76kimo** [comment]
[Done](https://github.com/tom76kimo/generator-elm-app/commit/84a1a649f03430e69f4a0376b86314adbaefa645)

**Comment by lpil** [comment]
Thanks!
